insert into STOCK_PRICE_DETAILS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values (101, 'Google', 1000.00);
insert into STOCK_PRICE_DETAILS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values (102, 'Apple', 2000.00);
insert into STOCK_PRICE_DETAILS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values (103, 'Microsoft', 3000.00);
insert into STOCK_PRICE_DETAILS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values (104, 'Amazon', 4000.00);
insert into STOCK_PRICE_DETAILS(STOCK_PRICE_ID, COMPANY_NAME, COMPANY_STOCK_PRICE) values (105, 'Facebook', 5000.00);